config/routes.rb
Rails.application.routes.draw do
  resources :offers
  resources :districts, only: :index, format: :js
  resources :localities, only: :index, format: :js
  resources :metro_stations, only: :index, format: :js
  resources :articles, only: [:index, :show]
  devise_for :users
  resources :support, only: [:index, :show], param: :slug

  ActiveAdmin.routes(self)

  root 'offers#index'

end

app/models/offer.rb
# == Schema Information
#
# Table name: offers
#
#  id                      :integer          not null, primary key
#  user_id                 :integer          not null
#  code                    :string(255)      not null
#  offer_type              :string(255)      not null
#  property_type           :string(255)      default("residential"), not null
#  category                :string(255)      not null
#  new_flat                :boolean          default(FALSE), not null
#  region_id               :integer          not null
#  district_id             :integer          not null
#  locality_id             :integer
#  address                 :string(255)
#  direction               :string(255)
#  distance                :float(24)
#  lat                     :decimal(10, 6)
#  lng                     :decimal(10, 6)
#  latlng_added_manually   :boolean          default(FALSE), not null
#  metro_station_id        :integer
#  metro_time_on_transport :float(24)
#  metro_time_on_foot      :float(24)
#  railway_station         :string(255)
#  images_list             :text(65535)
#  rooms                   :integer
#  rooms_offered           :integer
#  area                    :float(24)
#  living_space            :float(24)
#  rooms_spaces            :text(65535)
#  kitchen_space           :float(24)
#  lot_area                :float(24)
#  lot_type                :string(255)
#  area_unit               :string(255)
#  floor                   :integer
#  floors_total            :integer
#  title_uk                :string(255)
#  title_ru                :string(255)
#  title_en                :string(255)
#  description             :text(65535)
#  description_uk          :text(65535)
#  description_ru          :text(65535)
#  description_en          :text(65535)
#  renovation              :string(255)
#  quality                 :string(255)
#  open_plan               :boolean
#  rooms_type              :string(255)
#  phone                   :boolean
#  internet                :boolean
#  room_furniture          :boolean
#  kitchen_furniture       :boolean
#  television              :boolean
#  washing_machine         :boolean
#  refrigerator            :boolean
#  balcony                 :string(255)
#  bathroom_unit           :string(255)
#  floor_covering          :string(255)
#  window_view             :string(255)
#  building_name           :string(255)
#  building_type           :string(255)
#  building_series         :string(255)
#  building_phase          :string(255)
#  building_section        :string(255)
#  building_state          :string(255)
#  built_year              :integer
#  ready_quarter           :integer
#  lift                    :boolean
#  rubbish_chute           :boolean
#  is_elite                :boolean
#  parking                 :boolean
#  alarm                   :boolean
#  ceiling_height          :float(24)
#  pmg                     :boolean
#  toilet                  :string(255)
#  shower                  :string(255)
#  kitchen                 :boolean
#  pool                    :boolean
#  billiard                :boolean
#  sauna                   :boolean
#  heating_supply          :boolean
#  water_supply            :boolean
#  sewerage_supply         :boolean
#  electricity_supply      :boolean
#  gas_supply              :boolean
#  price                   :float(24)        not null
#  price_currency          :string(255)      not null
#  price_unit              :string(255)
#  price_period            :string(255)
#  price_m2                :float(24)
#  price_dollars           :float(24)
#  price_m2_dollars        :float(24)
#  not_for_agents          :boolean
#  haggle                  :boolean
#  mortgage                :boolean
#  prepayment              :float(24)
#  rent_pledge             :boolean
#  from_owner              :boolean          default(FALSE), not null
#  agent_fee               :float(24)
#  no_agent_fee            :boolean
#  deal_status             :string(255)
#  with_pets               :boolean
#  with_children           :boolean
#  manually_added          :boolean          default(TRUE), not null
#  expires_at              :datetime
#  urgent                  :boolean          default(FALSE), not null
#  phone_first             :string(255)      not null
#  phone_second            :string(255)
#  phone_third             :string(255)
#  phone_fourth            :string(255)
#  user_name               :string(255)
#  user_email              :string(255)
#  active                  :boolean          default(TRUE), not null
#  imported                :boolean          default(FALSE), not null
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class Offer < ActiveRecord::Base
  # Includes
  include OfferAliasAttributes

  # Before, after callbacks
  before_create :assign_code, unless: :imported?

  # Default scopes, default values (e.g. self.per_page =)
  TYPES = ['sale', 'rent']
  CATEGORIES = ['flat', 'room', 'house', 'cottage', 'townhouse', 'part_of_the_house', 'house_with_lot', 'country_house', 'lot', 'office', 'garage']
  RENOVATIONS = ['euro', 'design', 'rough_finish', 'in_need_of_repair', 'partial_renovation', 'finished', 'good']
  QUALITIES = ['good', 'excellent', 'normal', 'bad']
  BUILDING_TYPES = ['brick', 'silicate_brick', 'panel', 'monolith', 'foam_block', 'coquina', 'monolith_brick', 'monolith_block', 'wood_and_brick', 'inkerman_stone', 'skeleton', 'timber', 'metal']
  BATHROOM_UNITS = ['combined', 'separate']
  CURRENCIES = ['USD', 'UAH', 'EUR', 'GBP']
  AREA_UNITS = ['a', 'ha']
  PRICE_UNITS = ['m2', 'a', 'ha']
  PRICE_PERIODS = ['day', 'month']

  # Associations: belongs_to > has_one > has_many > has_and_belongs_to_many
  belongs_to :user
  belongs_to :region
  belongs_to :district
  belongs_to :locality

  # Validations: presence > by type > validates
  validates :offer_type, inclusion: { in: TYPES }
  validates :category, inclusion: { in: CATEGORIES }
  validates :region_id, :district_id, presence: true
  validates :locality_id, presence: true, unless: :imported?
  validates :price, presence: true
  validates :price_currency, inclusion: { in: CURRENCIES }
  validates :phone_first, presence: true
  validates :building_type, inclusion: { in: BUILDING_TYPES }, allow_blank: true
  validates :bathroom_unit, inclusion: { in: BATHROOM_UNITS }, allow_blank: true
  validates :area_unit, inclusion: { in: AREA_UNITS }, allow_blank: true
  validates :price_unit, inclusion: { in: PRICE_UNITS }, allow_blank: true
  validates :price_period, inclusion: { in: PRICE_PERIODS }, if: :rent?
  validates :price_period, absence: true, unless: :rent?

  # Other properties (e.g. accepts_nested_attributes_for)
  delegate :category, to: :locality, prefix: true, allow_nil: true

  # Model dictionaries, state machine
  serialize :rooms_spaces, Array
  alias_attribute :latitude, :lat
  alias_attribute :longitude, :lng

  # Scopes
  class << self
  end

  # Other model methods
  def inhabited_locality
    locality_category == 'district' ? district : locality
  end
  alias_method :city, :inhabited_locality

  def sub_locality
    locality if locality_category == 'district'
  end

  def phones=(values)
    self.phone_first, self.phone_second, self.phone_third, self.phone_fourth = values[0..3]
  end

  def rent?
    offer_type == 'rent'
  end

  # Private methods (for example: custom validators)
  private

    def assign_code
      write_attribute(:code, SecureRandom.uuid)
    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index, :show]
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  def index
    @offers = Offer.preload(:region, :district, :locality).order(updated_at: :desc).page(params[:page])
  end

  # GET /offers/1
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new(user: current_user)
    if current_user
      @offer.phone_first = current_user.phone_first
    end
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user

    if @offer.save
      redirect_to @offer, notice: 'Offer was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /offers/1
  def update
    if @offer.update(offer_params)
      redirect_to @offer, notice: 'Offer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /offers/1
  def destroy
    @offer.destroy
    redirect_to offers_url, notice: 'Offer was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def offer_params
      params[:offer].permit(:offer_type, :category, :region_id, :district_id, :locality_id, :price, :price_currency, :phone_first)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
  def areas_list(offer)
    if offer.living_area || offer.kitchen_area
      "#{offer.area}/#{offer.living_area || '-'}/#{offer.kitchen_area || '-'}"
    else
      "#{offer.area} #{I18n.t('sq_m')}"
    end
  end

  def floors_list(offer)
    if offer.floor && offer.floors_count
      "#{offer.floor}/#{offer.floors_count}"
    elsif offer.floor
      "#{offer.floor} #{I18n.t('offer.floor')}"
    elsif offer.floors_count
      "#{I18n.t('offer.floors_total')}: #{offer.floors_count}"
    end
  end
end

app/views/offers/_form.html.erb
<%= form_for @offer, html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :offer_type, t('offer.section.offer'), class: 'control-label col-md-4' %>
    <div class="col-md-2">
      <%= f.select :offer_type, Offer::TYPES.map { |type| [t("offer.type.#{type}"), type] }, { prompt: '' }, data: { placeholder: Offer.human_attribute_name('offer_type') }, style: 'width:120px;' %>
    </div>
    <div class="col-md-4">
    <%= f.select :category, Offer::CATEGORIES.map { |c| [t("offer.category.#{c}"), c] }, { prompt: '' }, data: { placeholder: Offer.human_attribute_name('category') } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :region_id, t('offer.section.location'), class: 'control-label col-md-4' %>
    <div class="col-md-2">
    <%= f.select :region_id, options_from_collection_for_select(Region.order(:"name_#{I18n.locale}"), 'id', 'name', selected: f.object.region_id), { prompt: '' }, data: { placeholder: Offer.human_attribute_name('region_id') }, autocomplete: 'off', style: 'width:140px' %>
    </div>
    <div class="col-md-3">
      <%= f.select :district_id, options_for_district_select(f.object.region_id, f.object.district_id), { prompt: '' }, data: { placeholder: (f.object.region_id ? Offer.human_attribute_name('district_id') : t('offers.form.placeholders.first_select_region')) }, autocomplete: 'off', style: 'width:190px' %>
    </div>
    <div class="col-md-3">
      <%= f.select :locality_id, options_for_locality_select(f.object.district_id, f.object.locality_id), { prompt: '' }, data: { placeholder: (f.object.district_id ? Offer.human_attribute_name('locality_id') :  t('offers.form.placeholders.first_select_district')) }, autocomplete: 'off', style: 'width:190px' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address, t('offer.section.address'), class: 'control-label col-md-4' %>
    <div class="col-md-8">
      <%= f.text_field :address, class: 'text_field form-control', placeholder: Offer.human_attribute_name('address') %>
    </div>
  </div>

  <div class="switched by_locality" data-category="['suburb','village']">
    <div class="form-group">
      <%= f.label :direction, class: 'control-label col-md-4' %>
      <div class="col-md-8">
        <%= f.text_field :direction, class: 'text_field form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :distance, class: 'control-label col-md-4' %>
      <div class="col-md-8">
        <%= f.number_field :distance, class: 'number_field form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :railway_station, class: 'control-label col-md-4' %>
      <div class="col-md-8">
        <%= f.text_field :railway_station, class: 'text_field form-control' %>
      </div>
    </div>
  </div>

  <div class="metro_station_details">
    <div class="form-group">
      <%= f.label :metro_station_id, class: 'control-label col-md-4' %>
      <div class="col-md-8">
        <%= f.select :metro_station_id, options_for_metro_station_select(f.object.district_id, f.object.locality.try(:category), f.object.metro_station_id), { prompt: '' }, data: { placeholder: Offer.human_attribute_name('metro_station_id') }, autocomplete: 'off', style: 'width:190px' %>
      </div>
    </div>
    <div class="form-group metro">
      <%= f.label :metro_time_on_transport, class: 'control-label col-md-4' %>
      <div class="col-md-8">
        <%= f.number_field :metro_time_on_transport, class: 'text_field form-control' %>
      </div>
    </div>
    <div class="form-group metro">
      <%= f.label :metro_time_on_foot, class: 'control-label col-md-4' %>
      <div class="col-md-8">
        <%= f.number_field :metro_time_on_foot, class: 'text_field form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group switched by_realty" data-realty="['flat','house','room']">
    <%= f.label :rooms, class: 'control-label col-md-4' %>
    <div class="col-md-8">
      <%= f.number_field :rooms, class: 'text_field form-control number' %>
    </div>
  </div>

  <div class="form-group switched by_realty" data-realty="['flat','room']">
    <%= f.label :area, class: 'control-label col-md-4' %>
    <div class="col-md-1">
      <%= f.number_field :area, class: 'text_field form-control number', placeholder: Offer.human_attribute_name('area_placeholder'), title: Offer.human_attribute_name('area') %>
    </div>
    <div class="col-md-1">
      <%= f.number_field :living_space, class: 'text_field form-control number', placeholder: Offer.human_attribute_name('living_space_placeholder'), title: Offer.human_attribute_name('living_space') %>
    </div>
    <div class="col-md-1">
      <%= f.number_field :kitchen_space, class: 'text_field form-control number', placeholder: Offer.human_attribute_name('kitchen_space_placeholder'), title: Offer.human_attribute_name('kitchen_space') %>
    </div>
  </div>

  <div class="form-group switched by_realty" data-realty="['house','lot']">
    <%= f.label :lot_area, class: 'control-label col-md-4' %>
    <div class="col-md-1">
      <%= f.number_field :lot_area, class: 'text_field form-control number' %>
    </div>
    <div class="col-md-2">
      <%= f.select :area_unit, [[t('offer.area_unit.acres'), 'acres'], [t('offer.area_unit.hectare'), 'hectare']] %>
    </div>
  </div>

  <div class="form-group switched by_realty" data-realty="['house','lot']">
    <%= f.label :lot_type, class: 'control-label col-md-4' %>
    <div class="col-md-8">
      <%= f.select :lot_type, [[t('offer.lot_type.individual_house_building'), 'individual_house_building'], [t('offer.lot_type.gardening'), 'gardening']] %>
    </div>
  </div>

  <div class="form-group switched by_realty" data-realty="['room']">
    <%= f.label :rooms_offered, class: 'control-label col-md-4' %>
    <div class="col-md-8">
      <%= f.number_field :rooms_offered, class: 'text_field form-control number' %>
    </div>
  </div>

  <div class="form-group switched by_realty" data-realty="['room']">
    <%= f.label :rooms_spaces, class: 'control-label col-md-4' %>
    <div class="col-md-8">
      <%= f.number_field :rooms_spaces, class: 'text_field form-control number' %>
    </div>
  </div>

  <div class="form-group switched by_realty" data-realty="['house','office','garage']">
    <%= f.label :area, class: 'control-label col-md-4' %>
    <div class="col-md-1">
      <%= f.number_field :area, class: 'text_field form-control number' %>
    </div>
    <div class="col-md-1" style="padding-top:5px;padding-left:25px;">
      <%= t('m2_html').html_safe %>
    </div>
  </div>

  <div class="form-group switched by_realty" data-realty="['flat','room','office']">
    <%= f.label :floor_and_floors_total, class: 'control-label col-md-4' %>
    <div class="col-md-1">
      <%= f.number_field :floor, class: 'text_field form-control number' %>
    </div>
    <div class="col-md-1">
      <%= f.number_field :floors_total, class: 'text_field form-control number' %>
    </div>
  </div>

  <div class="form-group switched by_realty" data-realty="['house']">
    <%= f.label :floors_total, class: 'control-label col-md-4' %>
    <div class="col-md-8">
      <%= f.number_field :floors_total, class: 'text_field form-control number' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'control-label col-md-4' %>
    <div class="col-md-8">
      <%= f.text_area :description, class: 'text_field form-control', cols: 100, rows: 10 %>
    </div>
  </div>

  <div class="form-group switched by_realty" data-realty="['flat','room']">
    <%= f.label :renovation, class: 'control-label col-md-4' %>
    <div class="col-md-8">
      <%= f.select :renovation, Offer::RENOVATIONS.map { |r| [t("offer.renovation.#{r}"), r] }, { prompt: '' }, data: { placeholder: Offer.human_attribute_name('renovation') }, style: 'width:160px;' %>
    </div>
  </div>

  <div class="form-group switched by_realty" data-realty="['flat','room']">
    <%= f.label :quality, class: 'control-label col-md-4' %>
    <div class="col-md-8">
      <%= f.select :quality, Offer::QUALITIES.map { |q| [t("offer.quality.#{q}"), q] }, { prompt: '' }, data: { placeholder: Offer.human_attribute_name('quality') }, style: 'width:160px;' %>
    </div>
  </div>

  <div class="form-group switched by_realty" data-realty="['flat','room','house','office','garage']">
    <%= f.label :building_type, class: 'control-label col-md-4' %>
    <div class="col-md-8">
      <%= f.select :building_type, Offer::BUILDING_TYPES.map { |r| [t("offer.building_type.#{r}"), r] }, { prompt: '' }, data: { placeholder: Offer.human_attribute_name('building_type') }, style: 'width:160px;' %>
    </div>
  </div>

  <div class="form-group switched by_realty" data-realty="['flat','room']">
    <%= f.label :bathroom_unit, class: 'control-label col-md-4' %>
    <div class="col-md-8">
      <%= f.select :bathroom_unit, Offer::BATHROOM_UNITS.map { |r| [t("offer.bathroom_unit.#{r}"), r] }, { prompt: '' }, data: { placeholder: Offer.human_attribute_name('bathroom_unit') }, style: 'width:160px;' %>
    </div>
  </div>

  <h3><%= t('.contact_and_price') %></h3>

  <div class="form-group">
    <%= f.label :price, class: 'control-label col-md-4' %>
    <div class="col-md-2">
      <%= f.number_field :price, class: 'text_field form-control price_input' %>
    </div>
    <div class="col-md-2">
      <%= f.select :price_currency, Offer::CURRENCIES.map { |r| [t("offer.price_currency.#{r}"), r] }, { prompt: '' }, data: { placeholder: Offer.human_attribute_name('price_currency') }, style: 'width:160px;' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :phone_first, class: 'control-label col-md-4' %>
    <div class="col-md-8">
      <%= f.text_field :phone_first, class: "form-control", placeholder: '+380987654321' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-8'>
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                  offers_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>
<% content_for :head do %>
  <%= javascript_tag "$(document).ready(function() { Offers.setupEditFormListener(); });" %>
<% end %>

app/views/offers/_offer.html.erb
<tr>
  <td>
    <div style="float: right;">
      <span class="label label-success label-as-badge" style="font-size: 1em;">
        <%= number_to_currency(offer.price, unit: offer.price_currency) %>
      </span>
    </div>
    <h3 style="display: inline; font-size: 1.4em;">
      <%= link_to offer.title, offer_path(offer) %>
    </h3>
    <p>
      <i><%= "#{offer.region.name}, #{offer.locality.name} #{areas_list(offer)}, #{floors_list(offer)}" %></i>
    </p>
    <p>
      <%= simple_format truncate(offer.description.to_s.mb_chars.downcase.strip.normalize.capitalize, length: 260) %>
    </p>
  </td>
</tr>

app/views/offers/edit.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial" 'form' %>

app/views/offers/index.html.erb
<%= link_to t('.new', default: t("helpers.links.new")), new_offer_path, class: 'btn btn-primary' %>

<%- model_class = Offer -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <%= render @offers %>
</table>

<div style="float:right;">
  <%= paginate @offers, theme: 'twitter-bootstrap-3' %>
</div>

app/views/offers/new.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>